name: linux-tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Python 3.3 and 3.4 have been removed since github won't provide these anymore
        python-version: [3.5, 3.6, 3.7, 3.8, 'pypy-3.6', 'pypy-3.7']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f ofunctions/requirements.txt ]; then pip install -r ofunctions/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -m flake8 --count --select=E9,F63,F7,F82 --show-source --statistics ofunctions
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        python -m flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics ofunctions
    - name: Execute tests and generate coverage report
      env:
        RUNNING_ON_GITHUB_ACTIONS: true
      run: |
        pip install coverage
        # Make sure we don't try the ping checks since they fail on github runners that don't allow pings (WTF !)
        # See https://github.com/actions/virtual-environments/issues/1519
        python -m coverage run -m pytest -s tests
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
